# Generated by Django 2.2.1 on 2019-07-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_detail', models.TextField()),
                ('second_detail', models.TextField()),
                ('third_detail', models.TextField()),
                ('website_name', models.CharField(max_length=20)),
            ],
        ),
    ]
