# Generated by Django 2.2.1 on 2019-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='has_won',
            field=models.CharField(default='lets play some TICTACTOE', max_length=40),
        ),
        migrations.AddField(
            model_name='website',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
