# Generated by Django 2.2.1 on 2019-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190724_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_name',
            field=models.CharField(default='Say my name', max_length=20),
        ),
    ]
