# Generated by Django 2.2.1 on 2019-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190724_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='about_author',
            field=models.TextField(default='about author'),
        ),
    ]
