# Generated by Django 2.2.1 on 2019-07-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_website_about_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='about_author',
        ),
    ]
