# Generated by Django 2.2.1 on 2019-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_website_about_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='fifth_detail',
            field=models.TextField(default='Saint'),
        ),
        migrations.AddField(
            model_name='website',
            name='first_service_detail',
            field=models.TextField(default='Saint'),
        ),
        migrations.AddField(
            model_name='website',
            name='forth_detail',
            field=models.TextField(default='Saint'),
        ),
        migrations.AddField(
            model_name='website',
            name='second_service_detail',
            field=models.TextField(default='Saint'),
        ),
        migrations.AddField(
            model_name='website',
            name='sixth_detail',
            field=models.TextField(default='Saint'),
        ),
        migrations.AddField(
            model_name='website',
            name='third_service_detail',
            field=models.TextField(default='Saint'),
        ),
    ]
