# Generated by Django 2.2.1 on 2019-07-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190729_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='fifth_detail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='first_detail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='forth_detail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='second_detail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='sixth_detail',
        ),
        migrations.RemoveField(
            model_name='website',
            name='third_detail',
        ),
    ]
