# Generated by Django 2.2.1 on 2019-07-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190729_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='first_service_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='second_service_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='third_service_detail',
            field=models.TextField(),
        ),
    ]
